{% set name = "matrepr" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matrepr-{{ version }}.tar.gz
  sha256: 971fa03d05ea672a456806c4c8385491570665b3e206356a17577ed9ec42fa12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - tabulate

test:
  imports:
    - matrepr
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - html5lib
    - scipy
    - python-graphblas
    - sparse
    - pytorch
    - tensorflow
  source_files:
    - tests/

about:
  home: https://github.com/alugowski/matrepr
  summary: Format matrices and tensors to HTML, string, and LaTeX, with Jupyter integration.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alugowski
